name: CSCI 151
highlighter: pygments
safe: false
baseurl: /151
exclude: [morea]
morea_theme: cerulean
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  #- Assessments
  #-Schedule